# Use the official Python image
FROM public.ecr.aws/docker/library/python:3.10-slim

ENV AWS_DEFAULT_REGION=us-east-1
ENV AWS_CONFIG_FILE=/home/appuser/.aws/config

ENV AWS_SHARED_CREDENTIALS_FILE=/home/appuser/.aws/credentials

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libexpat1 \
    vim \
    curl \
    libpq-dev \
    gcc

# Set work directory and copy files
WORKDIR /app
COPY requirements.txt ./
COPY app/ ./

# Install all dependencies (including streamlit) globally
RUN pip install --no-cache-dir -r requirements.txt

RUN useradd -ms /bin/bash appuser && \
    chown -R appuser:appuser /app

# Switch to non-root user
USER appuser
WORKDIR /app

# Expose Streamlit port
EXPOSE 8501

# Start the app
CMD ["streamlit", "run", "app.py", "--server.baseUrlPath=/report", "--server.enableCORS=false"]
