apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-app
  labels:
    app: report-app
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: webhook
    keel.sh/approvals: "none"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-app
  template:
    metadata:
      labels:
        app: report-app
    spec:
      serviceAccountName: streamlit-app-sa  # Use the IRSA-enabled service account
      containers:
        - name: report-app
          image: 248189947068.dkr.ecr.us-east-1.amazonaws.com/report-app:latest
          ports:
            - containerPort: 8501
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
