apiVersion: apps/v1
kind: Deployment
metadata:
  name: govsananga-deployment
  labels:
    app: govsananga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: govsananga
  template:
    metadata:
      labels:
        app: govsananga
    spec:
      containers:
      - name: govsananga
        image: 248189947068.dkr.ecr.us-east-1.amazonaws.com/govsananga:latest
        ports:
        - containerPort: 8501
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
