apiVersion: v1
kind: Service
metadata:
  name: report-app-service
  namespace: default
  labels:
    app: report-app
spec:
  selector:
    app: report-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
