[theme]
primaryColor = "#E30613"
backgroundColor = "#1f1f1f"
secondaryBackgroundColor = "#151515"
textColor = "#c8c8c8"
font = "sans serif"

base = "dark"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
toolbarMode = "minimal"
showErrorDetails = true
showSidebarNavigation = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
fastReruns = true

[logger]
level = "error"
enableLogging = false

[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false

[global]
developmentMode = false
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false
