[theme]
primaryColor = "#f8f9fa"              # Bootstrap primary blue
backgroundColor = "#f8f9fa"           # Light gray
secondaryBackgroundColor = "#dc3545"  # 🔴 Red sidebar (Bootstrap 'danger')
textColor = "#212529"                 # Soft black (Bootstrap dark)
font = "sans serif"
