[theme]
primaryColor = "#D13F42"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#FFFFFF"
font = "sans serif"

base = "dark"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
toolbarMode = "minimal"
showErrorDetails = true
showSidebarNavigation = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
fastReruns = true

[logger]
level = "error"
enableLogging = false

[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false

[global]
developmentMode = false
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false
