[theme]
primaryColor = "#D13F42"               # Azul escuro
backgroundColor = "#FFFFFF"            # Fundo geral branco
secondaryBackgroundColor = "#1D345B"   # Sidebar e menus escuros
textColor = "#1D345B"                  # Texto azul escuro (visível em fundo claro)
font = "sans serif"

