[theme]
primaryColor = "#f8f9fa"              # Bootstrap primary blue
backgroundColor = "#f8f9fa"           # Light gray
secondaryBackgroundColor = "#F0F2F6"  # Default Streamlit sidebar gray
textColor = "#212529"                 # Soft black (Bootstrap dark)
font = "sans serif"
