[theme]
primaryColor = "#1D345B"              
backgroundColor = "#f4f4f5"           # Soft neutral gray (not pure white)
secondaryBackgroundColor = "#D13F42"  # Subtle contrast for sidebar, etc.
textColor = "#212529"                 # Bootstrap dark – very readable
font = "sans serif"

